name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important for deployments
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: npm run build
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # For checkout only
          publish_dir: ./frontend/out # Your export directory
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} # This is CRUCIAL!